#!/bin/bash

# $1: searchdc
# $2: admindc
# $3: password
krb5conf ()
{
   domain=`hostname -d`
   realm=`echo $domain | sed 's/^\(.*\)$/\U\1/'`   
   fqdn=`hostname -f`
   echo "
[libdefaults]
	default_realm = $realm
#	kdc_timesync = 1
#	ccache_type = 4
#	forwardable = true
#	proxiable = true

[realms]
	$realm = {
		kdc = $fqdn
		admin_server = $fqdn
		default_domain = $realm
		database_module = openldap_ldapconf
	}
	
[domain_realm]
	.$domain = $realm
	$domain = $realm
[logging]
   kdc = FILE:/var/log/krb5/kdc.log
	admin_server = FILE:/var/log/krb5/kadmin.log
[appdefaults]
 pam = {
	     ticket_lifetime = 1d
        renew_lifetime = 1d
        forwardable = true
        proxiable = false
        retain_after_close = false
        minimum_uid = 2
        try_first_pass = true
        ignore_root = true

	     ldapservs = $fqdn
     	  ldapport = 636
	     passwd = /etc/passwd
        shadow = /etc/shadow
        groups = /etc/group

}
[dbdefaults]
        ldap_kerberos_container_dn = $1

[dbmodules]
        openldap_ldapconf = {
                db_library = kldap
                ldap_kdc_dn = \"$2\"

                # this object needs to have read rights on
                # the realm container, principal container and realm sub-trees
                ldap_kadmind_dn = \"$2\"

                # this object needs to have read and write rights on
                # the realm container, principal container and realm sub-trees
                ldap_service_password_file = /etc/krb5kdc/service.keyfile
                ldap_servers = ldaps://$fqdn
                ldap_conns_per_server = 5
        }
" > /etc/krb5.conf


echo "dn: olcDatabase={1}hdb,cn=config
add: olcDbIndex
olcDbIndex: krbPrincipalName eq,pres,sub" > krbprin.ldif
ldapmodify -f krbprin.ldif -D cn=admin,cn=config -w $3 -x -H ldaps://localhost


echo "dn: olcDatabase={1}hdb,cn=config
replace: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange,krbPrincipalKey by dn=\"$2\" write by anonymous auth by self write by * none
-
add: olcAccess
olcAccess: to dn.base=\"\" by * read
-
add: olcAccess
olcAccess: to * by dn=\"$2\" write by * read" > krbacl.ldif
ldapmodify -f krbacl.ldif -D cn=admin,cn=config -w $3 -x -H ldaps://localhost

if [ ! -d "/etc/krb5kdc" ] ; then 
	mkdir -p /etc/krb5kdc
fi

realm=`echo $domain | sed 's/^\(.*\)$/\U\1/'`
echo "*/admin@$realm *" > /var/lib/krb5kdc/kadm5.acl

kdb5_ldap_util -D  $2 create -subtrees $1 -r $realm -s -P $3 -H ldaps://localhost -w $3
kdb5_ldap_util -D  $2 stashsrvpw -f /etc/krb5kdc/service.keyfile $2 -w $3
ipaddr=`ifconfig eth0 | grep 'inet addr' | sed 's/^.*inet\ addr\:\(.*\)\ Bcast.*$/\1/'`
kadmin.local -q "addprinc -x dn=\"cn=`hostname`+ipHostNumber=$ipaddr,ou=hosts,$1\" -randkey host/$fqdn@$realm"
kadmin.local -q "ktadd -k /etc/krb5.keytab host/$fqdn@$realm"
kadmin.local -q "addprinc -pw $3 -x dn=\"$2\" root/admin"


}
