#!/bin/bash

# $1: searchdc
# $2: admindc
# $3: password
krb5conf ()
{
  while [ "$1" != "" ]; do
    case $1 in
      -p | --password )       shift
                              password=$1
                              ;;
      -s | --searchdc )       shift
                              searchdc=$1
                              ;;
      -a | --admindc )        shift
                              admindc=$1
                              ;;
      -f | --fqdn )           shift
                              fqdn=$1
                              ;;

    esac
    shift
  done

  if [ -z $fqdn ] ; then 
    fqdn=`hostname -f`
  fi 
  
  domain=`echo $fqdn | sed "s/^[A-Za-z0-9\/]*[A-Za-z0-9\/]\.//" `
  realm=`echo $domain | sed 's/^\(.*\)$/\U\1/'`   
  echo "domain: $domain"
  echo "realm: $realm"

  if [ ! -d "/var/log/krb5" ]; then
    mkdir -p /var/log/krb5
  fi  
echo "[libdefaults]
	default_realm = $realm
#	kdc_timesync = 1
#	ccache_type = 4
#	forwardable = true
#	proxiable = true

[realms]
	$realm = {
		kdc = $fqdn
		admin_server = $fqdn
		default_domain = $realm
		database_module = openldap_ldapconf
	}
	
[domain_realm]
	.$domain = $realm
	$domain = $realm
[logging]
  kdc = FILE:/var/log/krb5/kdc.log
	admin_server = FILE:/var/log/krb5/kadmin.log
[appdefaults]
  pam = {
	     ticket_lifetime = 1d
        renew_lifetime = 1d
        forwardable = true
        proxiable = false
        retain_after_close = false
        minimum_uid = 2
        try_first_pass = true
        ignore_root = true

	ldapservs = $fqdn
     	ldapport = 636
	passwd = /etc/passwd
        shadow = /etc/shadow
        groups = /etc/group

}
[dbdefaults]
        ldap_kerberos_container_dn = $searchdc

[dbmodules]
        openldap_ldapconf = {
                db_library = kldap
                ldap_kdc_dn = \"$admindc\"

                # this object needs to have read rights on
                # the realm container, principal container and realm sub-trees
                ldap_kadmind_dn = \"$admindc\"

                # this object needs to have read and write rights on
                # the realm container, principal container and realm sub-trees
                ldap_service_password_file = /etc/krb5kdc/service.keyfile
                ldap_servers = ldaps://$fqdn
                ldap_conns_per_server = 5
        }
" > /etc/krb5.conf


echo "dn: olcDatabase={1}hdb,cn=config
add: olcDbIndex
olcDbIndex: krbPrincipalName eq,pres,sub" > krbprin.ldif
ldapmodify -f krbprin.ldif -D cn=admin,cn=config -w $password -x -H ldaps://localhost


echo "dn: olcDatabase={1}hdb,cn=config
replace: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange,krbPrincipalKey by dn=\"$admindc\" write by anonymous auth by self write by * none
-
add: olcAccess
olcAccess: to dn.base=\"\" by * read
-
add: olcAccess
olcAccess: to * by dn=\"$admindc\" write by * read" > krbacl.ldif
ldapmodify -f krbacl.ldif -D cn=admin,cn=config -w $password -x -H ldaps://localhost

if [ ! -d "/etc/krb5kdc" ] ; then 
	mkdir -p /etc/krb5kdc
fi

echo "*/admin@$realm *" > /var/lib/krb5kdc/kadm5.acl

echo "Creating kerberos table in ldap"
# kdb5_ldap_util -D  $admindc create -subtrees $searchdc -r $realm -s -P $password -H ldaps://localhost -w $password
kdb5_ldap_util -D  $admindc -H ldaps://localhost -w $password create -subtrees $searchdc -r $realm -s -P $password
echo "Caching kerberos password"
kdb5_ldap_util -D  $admindc stashsrvpw -f /etc/krb5kdc/service.keyfile $admindc -w $password
ipaddr=`ip addr show eth0 | grep 'inet ' | sed 's/^.*inet\ \(.*\)\/.*$/\1/'`
kadmin.local -q "addprinc -x dn=\"cn=`hostname`+ipHostNumber=$ipaddr,ou=hosts,$searchdc\" -randkey host/$fqdn@$realm"
kadmin.local -q "ktadd -k /etc/krb5.keytab host/$fqdn@$realm"
kadmin.local -q "addprinc -pw $password -x dn=\"$admindc\" root/admin"


}
