#!/bin/bash

prep_slap_d ()
{
wget http://bind9-ldap.bayour.com/dnszone-schema.txt 

mv dnszone-schema.txt /etc/openldap/schema/dnszone.schema
chown ldap:ldap /etc/openldap/schema/dnszone.schema
chmod 
# mv /etc/openldap/slapd.conf /etc/openldap/slapd.conf.old
echo "
#
# See slapd.conf(5) for details on configuration options.
# This file should NOT be world readable.
#
include		/etc/openldap/schema/core.schema
include		/etc/openldap/schema/collective.schema       
include		/etc/openldap/schema/corba.schema                    
include		/etc/openldap/schema/cosine.schema           
include		/etc/openldap/schema/duaconf.schema 
include		/etc/openldap/schema/dhcp.schema
include		/etc/openldap/schema/dyngroup.schema			
include		/etc/openldap/schema/inetorgperson.schema
include		/etc/openldap/schema/kerberos.schema
include		/etc/openldap/schema/java.schema            
include		/etc/openldap/schema/misc.schema            
include		/etc/openldap/schema/nis.schema             
include		/etc/openldap/schema/openldap.schema        
include		/etc/openldap/schema/ppolicy.schema 
include		/etc/openldap/schema/pmi.schema
include		/etc/openldap/schema/dnszone.schema
# include		/etc/openldap/schema/rfc2307bis.schema

# Define global ACLs to disable default read access.

# Do not enable referrals until AFTER you have a working directory
# service AND an understanding of referrals.
#referral	ldap://root.openldap.org

pidfile		/var/run/openldap/slapd.pid
argsfile	/var/run/openldap/slapd.args

# Load dynamic backend modules:
modulepath	/usr/lib/openldap/openldap
moduleload	back_sock.so
moduleload	back_shell.so
moduleload	back_relay.so
moduleload	back_perl.so
moduleload	back_passwd.so
moduleload	back_null.so
moduleload	back_monitor.so
moduleload	back_meta.so
moduleload	back_ldap.so
moduleload	back_dnssrv.so

# Sample security restrictions
#	Require integrity protection (prevent hijacking)
#	Require 112-bit (3DES or better) encryption for updates
#	Require 63-bit encryption for simple bind
# security ssf=1 update_ssf=112 simple_bind=64

# Sample access control policy:
#	Root DSE: allow anyone to read it
#	Subschema (sub)entry DSE: allow anyone to read it
#	Other DSEs:
#		Allow self write access
#		Allow authenticated users read access
#		Allow anonymous users to authenticate
#	Directives needed to implement policy:
# access to dn.base=\"cn=config\" by  ${2} write
# access to dn.base=\"cn=Subschema\" by * read
access to *
   by dn=\"cn=admin,cn=config\" write
   by * read
#	by self write
#	by users read
#	by anonymous auth
#
# if no access controls are present, the default policy
# allows anyone and everyone to read anything but restricts
# updates to rootdn.  (e.g., \"access to * by * read\")
#
# rootdn can always read and write EVERYTHING!

#######################################################################
# BDB database definitions
#######################################################################
database config
rootdn \"cn=admin,cn=config\"
rootpw		${3}

#database	hdb

#suffix		\"${1}\"
#checkpoint	32	30
#directory	\"/var/lib/ldap\"
#index	objectClass	eq
" > /etc/openldap/slapd.conf
echo "dn: olcDatabase=hdb,cn=config
objectClass: olcDatabaseConfig
objectClass: olcHdbConfig
olcDatabase: {1}hdb
olcSuffix: ${1}
olcDbDirectory: /var/lib/ldap
olcRootDN: ${2}
olcRootPW: ${3}
olcDbConfig: set_cachesize 0 2097152 0
olcDbConfig: set_lk_max_objects 1500
olcDbConfig: set_lk_max_locks 1500
olcDbConfig: set_lk_max_lockers 1500
olcDbIndex: objectClass eq
olcLastMod: TRUE
olcDbCheckpoint: 512 30
olcAccess: to attrs=userPassword by dn=\"${2}\" write by anonymous auth by self write by * none
olcAccess: to attrs=shadowLastChange by self write by * read
olcAccess: to dn.base="" by * read
olcAccess: to * by dn=\"${2}\" write by * read" > backend.ldif

echo "# \$OpenLDAP$
# Example DB_CONFIG file for use with slapd(8) BDB/HDB databases.
#
# See the Oracle Berkeley DB documentation
#   <http://www.oracle.com/technology/documentation/berkeley-db/db/ref/env/db_config.html>
# for detail description of DB_CONFIG syntax and semantics.
#
# Hints can also be found in the OpenLDAP Software FAQ
#	<http://www.openldap.org/faq/index.cgi?file=2>
# in particular:
#   <http://www.openldap.org/faq/index.cgi?file=1075>

# Note: most DB_CONFIG settings will take effect only upon rebuilding
# the DB environment.

# one 0.25 GB cache
set_cachesize 0 268435456 1

# Data Directory
# set_data_dir /var/lib/ldap

# Transaction Log settings
set_lg_regionmax 262144
set_lg_bsize 2097152
#set_lg_dir logs

# Note: special DB_CONFIG flags are no longer needed for \"quick\"
# slapadd(8) or slapindex(8) access (see their -q option). 
" > /var/lib/ldap/DB_CONFIG

}
