#!/bin/bash
getstate ()
{
state=`cat ip_info | grep -i Region -C 1 | tail -1 | sed 's/^.*[\<]td[\>]\(.*\)[\<]\/td[\>].*$/\U\1/g'`;
case "$state" in 
"ALABAMA" ) state="AL"
		;; 
"ALASKA" ) state="AK"
		;; 
"ARIZONA" ) state="AZ"
		;; 
"ARKANSAS" ) state="AR"
		;; 
"CALIFORNIA" ) state="CA"
		;; 
"COLORADO" ) state="CO"
		;; 
"CONNECTICUT" ) state="CT"
		;; 
"DELAWARE" ) state="DE"
		;; 
"DISTRICT OF COLUMBIA" ) state="DC"
		;; 
"FLORIDA" ) state="FL"
		;; 
"GEORGIA" ) state="GA"
		;; 
"HAWAII" ) state="HI"
		;; 
"IDAHO" ) state="ID"
		;; 
"ILLINOIS" ) state="IL"
		;; 
"IOWA" ) state="IA"
		;; 
"KANSAS" ) state="KS"
		;; 
"KENTUCKY" ) state="KY"
		;; 
"LOUISIANA" ) state="LA"
		;; 
"MAINE" ) state="ME"
		;; 
"MARYLAND" ) state="MD"
		;; 
"MASSACHUSSETTS" ) state="MA"
		;; 
"MICHIGAN" ) state="MI"
		;; 
"MINNESOTA" ) state="MN"
		;; 
"MISSISSIPPI" ) state="MS"
		;; 
"MISSOURI" ) state="MO"
		;; 
"MONTANA" ) state="MT"
		;; 
"NEBRASKA" ) state="NE"
		;; 
"NEVADA" ) state="NV"
		;; 
"NEW HAMPSHIRE" ) state="NH"
		;; 
"NEW JERSEY" ) state="NJ"
		;; 
"NEW MEXICO" ) state="NM"
		;; 
"NEW YORK" ) state="NY"
		;; 
"NORTH CAROLINA" ) state="NC"
		;; 
"NORTH DAKOTA" ) state="ND"
		;; 
"OHIO" ) state="OH"
		;; 
"OKLAHOMA" ) state="OK"
		;; 
"OREGON" ) state="OR"
		;; 
"PENNSYLVANIA" ) state="PA"
		;; 
"RHODE ISLAND" ) state="RI"
		;; 
"SOUTH CAROLINA" ) state="SC"
		;; 
"SOUTH DAKOTA" ) state="SD"
		;; 
"TENNESSEE" ) state="TN"
		;; 
"TEXAS" ) state="TX"
		;; 
"UTAH" ) state="UT"
		;; 
"VERMONT" ) state="VT"
		;; 
"VIRGINIA" ) state="VA"
		;; 
"WASHINGTON" ) state="WA"
		;; 
"WEST VIRGINA" ) state="WV"
		;; 
"WISCONSIN" ) state="WI"
		;; 
"WYOMING" ) state="WY"
		;;
esac
}
